### ISSUE TITLE
Non Void Return Statements

### ISSUE THREAD

**Issue by ecwood** [FRC-Team-955/Team-955-Infinite-Recharge-2020#19]
2020_FRC/Team-955-Infinite-Recharge-2020/src/main/cpp/xy_align.cpp:62:1: warning: no return statement in function returning non-void [-Wreturn-type]

2020_FRC/Team-955-Infinite-Recharge-2020/src/main/cpp/function_toggle.cpp: In member function 'bool FunctionToggle::ToggleFunction()':
/home/bluepiggy49/2020_FRC/Team-955-Infinite-Recharge-2020/src/main/cpp/function_toggle.cpp:19:1: warning: no return statement in function returning non-void [-Wreturn-type]

**Comment by jjxfan** [comment]
All codes have been fixed for Non void return statements.
